name: art_pen
version: 2.0.2
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: DArt Pen is a Logo language. dartling is a domain model framework.
homepage: http://ondart.me/
documentation: http://goo.gl/OvQWwN
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  ednet_core:
    path: ../../../ednet_cms/packages/ednet_core
  dartling_default_app:
    path: ../ednet_dartling_default_app
